export enum Tool {
  AGENT_TOOL = 'AgentTool',
  CONNECTOR_TOOL = 'ConnectorTool',
  CREATE_ANOMALY_DETECTOR_TOOL = 'CreateAnomalyDetectorTool',
  INDEX_MAPPING_TOOL = 'IndexMappingTool',
  LIST_INDEX_TOOL = 'ListIndexTool',
  ML_MODEL_TOOL = 'MLModelTool',
  NEURAL_SPARSE_SEARCH_TOOL = 'NeuralSparseSearchTool',
  PPL_TOOL = 'PPLTool',
  RAG_TOOL = 'RAGTool',
  SEARCH_ALERTS_TOOL = 'SearchAlertsTool',
  SEARCH_ANOMALY_DETECTORS_TOOL = 'SearchAnomalyDetectorsTool',
  SEARCH_ANOMALY_RESULTS_TOOL = 'SearchAnomalyResultsTool',
  SEARCH_INDEX_TOOL = 'SearchIndexTool',
  SEARCH_MONITORS_TOOL = 'SearchMonitorsTool',
  VECTOR_DB_TOOL = 'VectorDBTool',
  VISUALIZATION_TOOL = 'VisualizationTool',
  WEB_SEARCH_TOOL = 'WebSearchTool',
}
