/*
 * Wazuh app - Wazuh CSV column keys
 * Copyright (C) 2015-2022 Wazuh, Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Find more information about this on the LICENSE file.
 */
export const KeyEquivalence: {[key: string]: string} = {
  id: 'ID',
  timestamp: 'Timestamp',
  url: 'URL',
  version: 'Version',
  'os.name': 'OS name',
  'os.version': 'OS version',
  'os.arch': 'OS version architecture',
  'os.build': 'OS version build',
  'os.codename': 'OS code name',
  'os.major': 'OS version major',
  'os.minor': 'OS version minor',
  'os.platform': 'OS platform',
  'os.uname': 'OS uname',
  status: 'Status',
  group: 'Group',
  ip: 'IP address',
  description: 'Description',
  tag: 'Tag',
  level: 'Level',
  conf_sum: 'Group checksum',
  merged_sum: 'Configuration checksum',
  hash: 'Checksum',
  filename: 'File',
  file: 'File',
  gdpr: 'GDPR',
  pci: 'PCI',
  hipaa: 'HIPAA',
  'nist-800-53': 'NIST 800-53',
  cis: 'CIS',
  event: 'Event',
  groups: 'Groups',
  name: 'Name',
  count: 'Count',
  'details.program_name': 'Program name',
  'details.order': 'Order',
  vendor: 'Vendor',
  type: 'Type',
  architecture: 'Architecture',
  node_name: 'Node',
  dateAdd: 'Registration date',
  manager: 'Manager',
  lastKeepAlive: 'Last keep alive',
  os: 'Operating system',
  path: 'Path',
  details: 'Details',
  position: 'Position',
  configSum: 'Group checksum',
  mergedSum: 'Configuration checksum',
  key: 'Key',
  scan_id: 'Scan ID',
  format: 'Format',
  scan_time: 'Scan date',
  state: 'State',
  mac: 'MAC',
  gateway: 'Gateway',
  dhcp: 'DHCP',
  iface: 'Interface',
  broadcast: 'Broadcast',
  proto: 'Protocol',
  address: 'Address',
  protocol: 'Protocol',
  netmask: 'Netmask',
  'local.ip': 'Local IP address',
  'remote.ip': 'Remote IP',
  'local.port': 'Local port',
  'remote.port': 'Remote port',
  euser: 'Effective user',
  egroup: 'Effective group',
  vm_size: 'VM size',
  processor: 'Processor',
  session: 'Session',
  tty: 'TTY',
  pid: 'PID',
  ppid: 'Parent PID',
  argvs: 'Argvs',
  nice: 'Priority',
  size: 'Size',
  uname: 'User',
  gname: 'Group',
  perm: 'Permissions',
  inode: 'Inode',
  uid: 'User ID',
  gid: 'Group ID',
  mtime: 'Last modified',
  priority: 'Priority',
  cmd: 'Command',
  nlwp: 'NLWP',
  process: 'Process',
  md5: 'MD5',
  sha1: 'SHA1',
  sha256: 'SHA256',
  title: 'Title',
  remediation: 'Remediation',
  references: 'References',
  result: 'Result',
  directory: 'Path(s)',
  rationale: 'Rationale',
  registry: 'Registry',
  date: 'Date',
  value: 'Value',
  location: 'Location',
  mtu: 'MTU',
  attributes: 'Attributes',
  policy_id: 'Policy ID',
  policy_ID: 'Policy ID',
  compliance: 'Compliance',
  rules: 'Rules',
  reason: 'Reason',
  registerIP: 'Register IP',
  hotfix: 'Update code',
  'scan.time': 'Registered by Wazuh at'
};
