/*
 * Wazuh app - Module for Overview/FIM visualizations
 * Copyright (C) 2015-2022 Wazuh, Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Find more information about this on the LICENSE file.
 */
export default [
  // {
  //   _id: 'Wazuh-App-Overview-FIM-Events-summary',
  //   _type: 'visualization',
  //   _source: {
  //     title: 'Events summary',
  //     visState: JSON.stringify({
  //       title: 'Events summary',
  //       type: 'line',
  //       params: {
  //         type: 'line',
  //         grid: { categoryLines: true, style: { color: '#eee' } },
  //         categoryAxes: [
  //           {
  //             id: 'CategoryAxis-1',
  //             type: 'category',
  //             position: 'bottom',
  //             show: true,
  //             style: {},
  //             scale: { type: 'linear' },
  //             labels: { show: true, filter: true, truncate: 100 },
  //             title: {},
  //           },
  //         ],
  //         valueAxes: [
  //           {
  //             id: 'ValueAxis-1',
  //             name: 'LeftAxis-1',
  //             type: 'value',
  //             position: 'left',
  //             show: true,
  //             style: {},
  //             scale: { type: 'linear', mode: 'normal' },
  //             labels: { show: true, rotate: 0, filter: false, truncate: 100 },
  //             title: { text: 'Alerts' },
  //           },
  //         ],
  //         seriesParams: [
  //           {
  //             show: 'true',
  //             type: 'line',
  //             mode: 'normal',
  //             data: { label: 'Alerts', id: '1' },
  //             valueAxis: 'ValueAxis-1',
  //             drawLinesBetweenPoints: true,
  //             showCircles: true,
  //           },
  //         ],
  //         addTooltip: true,
  //         addLegend: false,
  //         legendPosition: 'right',
  //         times: [],
  //         addTimeMarker: false,
  //       },
  //       aggs: [
  //         {
  //           id: '1',
  //           enabled: true,
  //           type: 'count',
  //           schema: 'metric',
  //           params: { customLabel: 'Alerts' },
  //         },
  //         {
  //           id: '2',
  //           enabled: true,
  //           type: 'date_histogram',
  //           schema: 'segment',
  //           params: { field: 'timestamp' },
  //         },
  //       ],
  //     }),
  //     uiStateJSON: '{}',
  //     description: '',
  //     version: 1,
  //     kibanaSavedObjectMeta: {
  //       searchSourceJSON: JSON.stringify({
  //         index: 'wazuh-alerts',
  //         query: { query: '', language: 'lucene' },
  //         filter: [],
  //       }),
  //     },
  //   },
  // },
  // {
  //   _id: 'Wazuh-App-Overview-FIM-Top-5-rules',
  //   _type: 'visualization',
  //   _source: {
  //     title: 'Top 5 rules',
  //     visState: JSON.stringify({
  //       title: 'Export rule distr',
  //       type: 'pie',
  //       params: {
  //         type: 'pie',
  //         addTooltip: true,
  //         addLegend: true,
  //         legendPosition: 'right',
  //         isDonut: true,
  //         labels: {
  //           show: false,
  //           values: true,
  //           last_level: true,
  //           truncate: 100,
  //         },
  //       },
  //       aggs: [
  //         {
  //           id: '1',
  //           enabled: true,
  //           type: 'count',
  //           schema: 'metric',
  //           params: { field: 'rule.level' },
  //         },
  //         {
  //           id: '2',
  //           enabled: true,
  //           type: 'terms',
  //           schema: 'segment',
  //           params: {
  //             field: 'rule.description',
  //             size: 5,
  //             order: 'desc',
  //             orderBy: '1',
  //             otherBucket: false,
  //             otherBucketLabel: 'Other',
  //             missingBucket: false,
  //             missingBucketLabel: 'Missing',
  //           },
  //         },
  //       ],
  //     }),
  //     uiStateJSON: '{}',
  //     description: '',
  //     version: 1,
  //     kibanaSavedObjectMeta: {
  //       searchSourceJSON: JSON.stringify({
  //         index: 'wazuh-alerts',
  //         query: { query: '', language: 'lucene' },
  //         filter: [],
  //       }),
  //     },
  //   },
  // },
  // {
  //   _id: 'Wazuh-App-Overview-FIM-Top-5-agents-pie',
  //   _type: 'visualization',
  //   _source: {
  //     title: 'Top 5 agents pie',
  //     visState: JSON.stringify({
  //       title: 'Top 5 agents pie',
  //       type: 'pie',
  //       params: {
  //         type: 'pie',
  //         addTooltip: true,
  //         addLegend: true,
  //         legendPosition: 'right',
  //         isDonut: true,
  //         labels: {
  //           show: false,
  //           values: true,
  //           last_level: true,
  //           truncate: 100,
  //         },
  //       },
  //       aggs: [
  //         {
  //           id: '1',
  //           enabled: true,
  //           type: 'count',
  //           schema: 'metric',
  //           params: {},
  //         },
  //         {
  //           id: '2',
  //           enabled: true,
  //           type: 'terms',
  //           schema: 'segment',
  //           params: {
  //             field: 'agent.name',
  //             size: 5,
  //             order: 'desc',
  //             orderBy: '1',
  //             otherBucket: false,
  //             otherBucketLabel: 'Other',
  //             missingBucket: false,
  //             missingBucketLabel: 'Missing',
  //           },
  //         },
  //       ],
  //     }),
  //     uiStateJSON: '{}',
  //     description: '',
  //     version: 1,
  //     kibanaSavedObjectMeta: {
  //       searchSourceJSON: JSON.stringify({
  //         index: 'wazuh-alerts',
  //         query: { language: 'lucene', query: '' },
  //         filter: [],
  //       }),
  //     },
  //   },
  // },
  // {
  //   _id: 'Wazuh-App-Overview-FIM-Common-actions',
  //   _type: 'visualization',
  //   _source: {
  //     title: 'Common actions',
  //     visState: JSON.stringify({
  //       title: 'Common actions',
  //       type: 'pie',
  //       params: {
  //         type: 'pie',
  //         addTooltip: true,
  //         addLegend: true,
  //         legendPosition: 'right',
  //         isDonut: false,
  //         labels: {
  //           show: false,
  //           values: true,
  //           last_level: true,
  //           truncate: 100,
  //         },
  //       },
  //       aggs: [
  //         {
  //           id: '1',
  //           enabled: true,
  //           type: 'count',
  //           schema: 'metric',
  //           params: {},
  //         },
  //         {
  //           id: '2',
  //           enabled: true,
  //           type: 'terms',
  //           schema: 'segment',
  //           params: {
  //             field: 'syscheck.event',
  //             size: 5,
  //             order: 'desc',
  //             orderBy: '1',
  //             otherBucket: false,
  //             otherBucketLabel: 'Other',
  //             missingBucket: false,
  //             missingBucketLabel: 'Missing',
  //           },
  //         },
  //       ],
  //     }),
  //     uiStateJSON: '{}',
  //     description: '',
  //     version: 1,
  //     kibanaSavedObjectMeta: {
  //       searchSourceJSON: JSON.stringify({
  //         index: 'wazuh-alerts',
  //         query: { language: 'lucene', query: '' },
  //         filter: [],
  //       }),
  //     },
  //   },
  // },
  {
    _id: 'Wazuh-App-Agents-FIM-Alerts-by-action-over-time',
    _source: {
      title: 'Alerts by action over time',
      visState: JSON.stringify({
        title: 'Alerts by action over time',
        type: 'area',
        aggs: [
          {
            id: '1',
            enabled: true,
            type: 'count',
            params: {
              customLabel: 'Count',
            },
            schema: 'metric',
          },
          {
            id: '3',
            enabled: true,
            type: 'terms',
            params: {
              field: 'syscheck.event',
              orderBy: '1',
              order: 'desc',
              size: 5,
              otherBucket: false,
              otherBucketLabel: 'Other',
              missingBucket: false,
              missingBucketLabel: 'Missing',
            },
            schema: 'group',
          },
          {
            id: '2',
            enabled: true,
            type: 'date_histogram',
            params: {
              field: 'timestamp',
              timeRange: {
                from: 'now-1M',
                to: 'now',
              },
              useNormalizedOpenSearchInterval: true,
              scaleMetricValues: false,
              interval: 'auto',
              drop_partials: false,
              min_doc_count: 1,
              extended_bounds: {},
            },
            schema: 'segment',
          },
        ],
        params: {
          type: 'area',
          grid: {
            categoryLines: false,
          },
          categoryAxes: [
            {
              id: 'CategoryAxis-1',
              type: 'category',
              position: 'bottom',
              show: true,
              style: {},
              scale: {
                type: 'linear',
              },
              labels: {
                show: true,
                filter: true,
                truncate: 100,
              },
              title: {},
            },
          ],
          valueAxes: [
            {
              id: 'ValueAxis-1',
              name: 'LeftAxis-1',
              type: 'value',
              position: 'left',
              show: true,
              style: {},
              scale: {
                type: 'linear',
                mode: 'normal',
              },
              labels: {
                show: true,
                rotate: 0,
                filter: false,
                truncate: 100,
              },
              title: {
                text: 'Count',
              },
            },
          ],
          seriesParams: [
            {
              show: true,
              type: 'area',
              mode: 'stacked',
              data: {
                label: 'Count',
                id: '1',
              },
              drawLinesBetweenPoints: true,
              lineWidth: 2,
              showCircles: true,
              interpolate: 'cardinal',
              valueAxis: 'ValueAxis-1',
            },
          ],
          addTooltip: true,
          addLegend: true,
          legendPosition: 'left',
          times: [],
          addTimeMarker: false,
          thresholdLine: {
            show: false,
            value: 10,
            width: 1,
            style: 'full',
            color: '#E7664C',
          },
          labels: {},
        },
      }),
      uiStateJSON: '{}',
      description: '',
      version: 1,
      kibanaSavedObjectMeta: {
        searchSourceJSON: JSON.stringify({
          index: 'wazuh-alerts',
          filter: [],
          query: { query: '', language: 'lucene' },
        }),
      },
    },
    _type: 'visualization',
  },
  {
    _id: 'Wazuh-App-Overview-FIM-Recent-Events',
    _type: 'visualization',
    _source: {
      title: 'Recent events',
      visState: JSON.stringify({
        title: 'Recent events',
        type: 'table',
        aggs: [
          {
            id: '1',
            enabled: true,
            type: 'count',
            params: {
              customLabel: 'Count',
            },
            schema: 'metric',
          },
          {
            id: '2',
            enabled: true,
            type: 'date_histogram',
            params: {
              field: 'timestamp',
              timeRange: {
                from: 'now-1M',
                to: 'now',
              },
              useNormalizedOpenSearchInterval: true,
              scaleMetricValues: false,
              interval: 'auto',
              drop_partials: false,
              min_doc_count: 1,
              extended_bounds: {},
              customLabel: 'Time',
            },
            schema: 'bucket',
          },
          {
            id: '3',
            enabled: true,
            type: 'terms',
            params: {
              field: 'syscheck.event',
              orderBy: '1',
              order: 'desc',
              size: 5,
              otherBucket: false,
              otherBucketLabel: 'Other',
              missingBucket: false,
              missingBucketLabel: 'Missing',
              customLabel: 'Action',
            },
            schema: 'bucket',
          },
          {
            id: '4',
            enabled: true,
            type: 'terms',
            params: {
              field: 'syscheck.path',
              orderBy: '1',
              order: 'desc',
              size: 5,
              otherBucket: false,
              otherBucketLabel: 'Other',
              missingBucket: false,
              missingBucketLabel: 'Missing',
              customLabel: 'Description',
            },
            schema: 'bucket',
          },
          {
            id: '5',
            enabled: true,
            type: 'terms',
            params: {
              field: 'rule.level',
              orderBy: '1',
              order: 'desc',
              size: 5,
              otherBucket: false,
              otherBucketLabel: 'Other',
              missingBucket: false,
              missingBucketLabel: 'Missing',
              customLabel: 'Level',
            },
            schema: 'bucket',
          },
          {
            id: '6',
            enabled: true,
            type: 'terms',
            params: {
              field: 'rule.id',
              orderBy: '1',
              order: 'desc',
              size: 5,
              otherBucket: false,
              otherBucketLabel: 'Other',
              missingBucket: false,
              missingBucketLabel: 'Missing',
              customLabel: 'Rule ID',
            },
            schema: 'bucket',
          },
        ],
        params: {
          perPage: 10,
          showPartialRows: false,
          showMetricsAtAllLevels: false,
          showTotal: false,
          totalFunc: 'sum',
          percentageCol: '',
        },
      }),
      uiStateJSON: JSON.stringify({
        vis: { params: { sort: { columnIndex: 3, direction: 'desc' } } },
      }),
      description: '',
      version: 1,
      kibanaSavedObjectMeta: {
        searchSourceJSON: JSON.stringify({
          index: 'wazuh-alerts',
          query: { query: '', language: 'lucene' },
          filter: [
            {
              meta: {
                index: 'wazuh-alerts',
                negate: false,
                disabled: false,
                alias: null,
                type: 'phrase',
                key: 'rule.groups',
                value: 'syscheck',
                params: { query: 'syscheck', type: 'phrase' },
              },
              query: {
                match: { 'rule.groups': { query: 'syscheck', type: 'phrase' } },
              },
              $state: { store: 'appState' },
            },
          ],
        }),
      },
    },
  },
  // {
  //   _id: 'Wazuh-App-Overview-FIM-Alerts-summary',
  //   _type: 'visualization',
  //   _source: {
  //     title: 'Alerts summary',
  //     visState: JSON.stringify({
  //       title: 'Alerts summary',
  //       type: 'table',
  //       params: {
  //         perPage: 10,
  //         showPartialRows: false,
  //         showMeticsAtAllLevels: false,
  //         sort: { columnIndex: 3, direction: 'desc' },
  //         showTotal: false,
  //         showToolbar: true,
  //         totalFunc: 'sum',
  //       },
  //       aggs: [
  //         {
  //           id: '1',
  //           enabled: true,
  //           type: 'count',
  //           schema: 'metric',
  //           params: {},
  //         },
  //         {
  //           id: '2',
  //           enabled: true,
  //           type: 'terms',
  //           schema: 'bucket',
  //           params: {
  //             field: 'agent.name',
  //             otherBucket: false,
  //             otherBucketLabel: 'Other',
  //             missingBucket: false,
  //             missingBucketLabel: 'Missing',
  //             size: 1000,
  //             order: 'desc',
  //             orderBy: '1',
  //             customLabel: 'Agent',
  //           },
  //         },
  //         {
  //           id: '3',
  //           enabled: true,
  //           type: 'terms',
  //           schema: 'bucket',
  //           params: {
  //             field: 'syscheck.path',
  //             otherBucket: false,
  //             otherBucketLabel: 'Other',
  //             missingBucket: false,
  //             missingBucketLabel: 'Missing',
  //             size: 20,
  //             order: 'desc',
  //             orderBy: '1',
  //             customLabel: 'Path',
  //           },
  //         },
  //         {
  //           id: '4',
  //           enabled: true,
  //           type: 'terms',
  //           schema: 'bucket',
  //           params: {
  //             field: 'syscheck.event',
  //             otherBucket: false,
  //             otherBucketLabel: 'Other',
  //             missingBucket: false,
  //             missingBucketLabel: 'Missing',
  //             size: 12,
  //             order: 'desc',
  //             orderBy: '1',
  //             customLabel: 'Action',
  //           },
  //         },
  //       ],
  //     }),
  //     uiStateJSON: JSON.stringify({
  //       vis: { params: { sort: { columnIndex: 3, direction: 'desc' } } },
  //     }),
  //     description: '',
  //     version: 1,
  //     kibanaSavedObjectMeta: {
  //       searchSourceJSON: JSON.stringify({
  //         index: 'wazuh-alerts',
  //         filter: [],
  //         query: { query: '', language: 'lucene' },
  //       }),
  //     },
  //   },
  // },
];
