export const AGENTS_PAGE = {
  firstAgentList: '[data-test-subj="row-001"]',
  agSecurityEventsLink: ':nth-child(1) > .euiSideNav > .euiSideNav__content > .euiSideNavItem--root > .euiSideNavItem__items > :nth-child(1) > .euiSideNavItemButton > .euiSideNavItemButton__content > .euiSideNavItemButton__label > .euiFlexGroup > .euiFlexItem',
  agIntegrityMonitoringLink: ':nth-child(1) > .euiSideNav > .euiSideNav__content > .euiSideNavItem--root > .euiSideNavItem__items > :nth-child(2) > .euiSideNavItemButton > .euiSideNavItemButton__content > .euiSideNavItemButton__label > .euiFlexGroup > .euiFlexItem',
  agSCALink: ':nth-child(2) > .euiSideNav > .euiSideNav__content > .euiSideNavItem--root > .euiSideNavItem__items > :nth-child(3) > .euiSideNavItemButton > .euiSideNavItemButton__content > .euiSideNavItemButton__label > .euiFlexGroup > .euiFlexItem',
  agSystemAuditingLink: ':nth-child(2) > .euiSideNav > .euiSideNav__content > .euiSideNavItem--root > .euiSideNavItem__items > :nth-child(2) > .euiSideNavItemButton > .euiSideNavItemButton__content > .euiSideNavItemButton__label > .euiFlexGroup > .euiFlexItem',
  agVulnerabilitiesLink: ':nth-child(3) > .euiSideNav > .euiSideNav__content > .euiSideNavItem--root > .euiSideNavItem__items > :nth-child(1) > .euiSideNavItemButton > .euiSideNavItemButton__content > .euiSideNavItemButton__label > .euiFlexGroup > .euiFlexItem',
  agMitreAttackLink: ':nth-child(3) > .euiSideNav > .euiSideNav__content > .euiSideNavItem--root > .euiSideNavItem__items > :nth-child(2) > .euiSideNavItemButton > .euiSideNavItemButton__content > .euiSideNavItemButton__label > .euiFlexGroup > .euiFlexItem',
  moreLink: '//*[contains(@class,"wz-module-header-agent-main")]//*/button//*/span[contains(text(),"More")]',
  agPolicyMonitoring: ':nth-child(2) > .euiSideNav > .euiSideNav__content > .euiSideNavItem--root > .euiSideNavItem__items > :nth-child(1) > .euiSideNavItemButton > .euiSideNavItemButton__content > .euiSideNavItemButton__label > .euiFlexGroup > .euiFlexItem',
  agPCIDSS: ':nth-child(4) > .euiSideNav > .euiSideNav__content > .euiSideNavItem--root > .euiSideNavItem__items > :nth-child(1) > .euiSideNavItemButton > .euiSideNavItemButton__content > .euiSideNavItemButton__label > .euiFlexGroup > .euiFlexItem',
  agNIST: ':nth-child(4) > .euiSideNav > .euiSideNav__content > .euiSideNavItem--root > .euiSideNavItem__items > :nth-child(2) > .euiSideNavItemButton > .euiSideNavItemButton__content > .euiSideNavItemButton__label > .euiFlexGroup > .euiFlexItem',
  agTSC: ':nth-child(4) > .euiSideNav > .euiSideNav__content > .euiSideNavItem--root > .euiSideNavItem__items > :nth-child(3) > .euiSideNavItemButton > .euiSideNavItemButton__content > .euiSideNavItemButton__label > .euiFlexGroup > .euiFlexItem',
  statusChart: '.agents-status-pie .euiCard .euiCard__content  .euiFlexGroup--gutterLarge',
  agentDetails: 'euiFlexItem euiFlexItem--flexGrowZero agents-details-card',
  deployNewAgentButton: '//span[contains(text(),"Deploy new agent")]',
  exploreAgentButton: '.wz-module-header-nav .euiFlexItem .euiToolTipAnchor .euiButtonEmpty .euiButtonContent .euiButtonEmpty__text:contains("Explore agent")',
  firstAgentDisplayed: '.euiModal .euiTable .euiTableRow:nth-child(1)',
  unPinnedAgentButton: '.wz-module-header-nav .euiFlexItem .euiToolTipAnchor .euiButtonIcon[aria-label="Unpin agent"]',
  secundAgentDisplayed: '.euiModal .euiTable .euiTableRow:nth-child(2)',
  agentID: '.euiModal .euiTable .euiTableRow:nth-child(1) .euiTableRowCell:nth-child(1) .euiTableCellContent__text',
};
