import { ToolDefinition } from '../types';
import { clampLimit, limitProperty, objectSchema } from './common';

const ENABLED_VALUES = ['enabled', 'disabled', 'any'] as const;

/** Confirmed live: `detector.source` only takes these two values (unlike the four-space model of
 * get_rules/get_threat_intel_components' `wazuh-threatintel-*` content) -- a distinct vocabulary,
 * not reused from SECURITY_ANALYTICS_SPACES. */
const DETECTOR_SOURCES = ['custom', 'standard'] as const;

/**
 * OpenSearch Security Analytics detector definitions -- which detectors exist, what they monitor,
 * and where their generated alerts/findings live. `.opensearch-sap-detectors-config` is a single
 * fixed index (not a `wazuh-*` family), confirmed live to be indexer-reachable, with the whole
 * document nested under a `detector` object (mapped `type: nested`) -- filtering requires a
 * `nested` query wrapper, not a plain top-level `term`. `detector_type` is free text (vendor/
 * integration name, e.g. "suricata", "aws", "linux"), not a curated enum -- confirmed live to have
 * more distinct values than are worth enumerating. This is a listing tool only: it surfaces each
 * detector's own `alert_index`/`findings_index` references (which vary per detector_type) as
 * row-only detail, but does not yet query alerts/findings generated by these detectors -- a
 * deliberate scope decision, left for a future change.
 */
export const getDetectorsTool: ToolDefinition = {
  spec: {
    name: 'get_detectors',
    description:
      'Lists Security Analytics detector definitions (which detectors exist, what indices they ' +
      'monitor, whether they are enabled). Use for "which detectors are configured/active" ' +
      'questions. Not for the alerts/findings a detector generated -- that is out of this ' +
      "tool's scope.",
    parameters: objectSchema({
      enabled: {
        type: 'string',
        description:
          'Filter by whether the detector is enabled. Defaults to "enabled" (the common ' +
          '"active detectors" intent). Use "any" to include disabled detectors too.',
        enum: [...ENABLED_VALUES],
      },
      detector_type: {
        type: 'string',
        description:
          'Filter by one exact detector type/integration name, e.g. "suricata".',
      },
      source: {
        type: 'string',
        description: 'Filter by detector source. Omit to search across both.',
        enum: [...DETECTOR_SOURCES],
      },
      limit: limitProperty(
        'Max number of detectors to return (default 20, max 500).',
      ),
    }),
  },
  target: 'indexer',
  tier: 'T1',
  buildRequest(params) {
    const enabled =
      typeof params.enabled === 'string' &&
      (ENABLED_VALUES as readonly string[]).includes(params.enabled)
        ? params.enabled
        : 'enabled';
    const detectorType =
      typeof params.detector_type === 'string'
        ? params.detector_type.trim()
        : undefined;
    const source =
      typeof params.source === 'string' &&
      (DETECTOR_SOURCES as readonly string[]).includes(params.source)
        ? params.source
        : undefined;
    const limit = clampLimit(params.limit, 20, 500);

    const nestedFilter: Record<string, unknown>[] = [];
    if (enabled !== 'any') {
      nestedFilter.push({
        term: { 'detector.enabled': enabled === 'enabled' },
      });
    }
    if (detectorType) {
      nestedFilter.push({ term: { 'detector.detector_type': detectorType } });
    }
    if (source) {
      nestedFilter.push({ term: { 'detector.source': source } });
    }

    const query =
      nestedFilter.length > 0
        ? {
            nested: {
              path: 'detector',
              query: { bool: { filter: nestedFilter } },
            },
          }
        : { match_all: {} };

    return {
      target: 'indexer',
      index: '.opensearch-sap-detectors-config',
      body: {
        query,
        _source: [
          'detector.name',
          'detector.detector_type',
          'detector.enabled',
          'detector.source',
          'detector.last_update_time',
          'detector.schedule',
          'detector.alert_index',
          'detector.findings_index',
        ],
        sort: ['_doc'],
        size: limit,
      },
    };
  },
  tableSpec: {
    columns: [
      { field: 'detector.name', label: 'Name' },
      { field: 'detector.detector_type', label: 'Type' },
      { field: 'detector.enabled', label: 'Enabled' },
      { field: 'detector.source', label: 'Source' },
    ],
    // Row-only: last_update_time (write-time, not analyst-facing at a glance), schedule (nested
    // cron/period object), and the alert_index/findings_index references this tool deliberately
    // does not query yet (see doc comment above).
    rowFields: [
      'detector.last_update_time',
      'detector.schedule',
      'detector.alert_index',
      'detector.findings_index',
    ],
  },
  digest: {
    sampleColumns: [
      'detector.name',
      'detector.detector_type',
      'detector.enabled',
      'detector.source',
    ],
  },
};
