version: "3"

# Parameters:
# -------------
#   - APP: osd (OpenSearch Dashboards) or kbn (Kibana)
#   - VERSION: OpenSearch Dashboards / Kibana version
#   - REPO: Path to the Wazuh app repository
#   - JEST_ARGS: (optional) Jest CLI options. See https://jestjs.io/docs/cli
# Example:
# -------------
#   - APP="osd" VERSION="2.6.0"  REPO=$WZ_HOME JEST_ARGS="--runInBand --ci" docker-compose up
#   - APP="kbn" VERSION="7.10.2" REPO=$WZ_HOME JEST_ARGS="--runInBand --ci" docker-compose up

services:
  test_runner:
    container_name: jest
    image:  quay.io/wazuh/$APP-dev:$VERSION
    working_dir: /home/node/kbn/plugins/wazuh
    volumes:
      - $REPO:/home/node/kbn/plugins/wazuh
    command: /bin/bash -c '
        yarn;
        yarn test:jest $JEST_ARGS
      '