import {
  getAgentCommandsStepStatus,
  getOSSelectorStepStatus,
  getServerAddressStepStatus,
  getServerCredentialsStepStatus,
  getOptionalParameterStepStatus,
  showCommandsSections,
  getIncompleteSteps,
  getInvalidFields,
} from './enroll-agent-steps-status-services';

describe('status steps', () => {
  it.each`
    title                                      | form                                               | resultStatus
    ${'Operating system step status current'}  | ${{ operatingSystemSelection: { value: '' } }}     | ${'current'}
    ${'Operating system step status complete'} | ${{ operatingSystemSelection: { value: 'test' } }} | ${'complete'}
  `('$title', ({ form, resultStatus }) => {
    expect(getOSSelectorStepStatus(form)).toBe(resultStatus);
  });

  it.each`
    title                                                                 | form                                                                                                                              | resultStatus
    ${'Server address step status disabled: no operating system defined'} | ${{ operatingSystemSelection: { value: '', error: null }, serverAddress: { value: '', error: null } }}                            | ${'disabled'}
    ${'Server address step status disabled: operating system has error'}  | ${{ operatingSystemSelection: { value: 'test', error: 'error' }, serverAddress: { value: '', error: null } }}                     | ${'disabled'}
    ${'Server address step status current: server address is empty'}      | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: '', error: null } }}                        | ${'current'}
    ${'Server address step status current: server address has error'}     | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: '', error: 'error' } }}                     | ${'current'}
    ${'Server address step status complete'}                              | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null } }} | ${'complete'}
  `('$title', ({ form, resultStatus }) => {
    expect(getServerAddressStepStatus(form)).toBe(resultStatus);
  });

  it.each`
    title                                                              | form                                                                                                                                                                                                                      | resultStatus
    ${'Credentials step status disabled: no operating system defined'} | ${{ operatingSystemSelection: { value: '', error: null }, serverAddress: { value: 'https://localhost:55000', error: null } }}                                                                                             | ${'disabled'}
    ${'Credentials step status disabled: operating system has error'}  | ${{ operatingSystemSelection: { value: '', error: 'error' }, serverAddress: { value: 'https://localhost:55000', error: null } }}                                                                                          | ${'disabled'}
    ${'Credentials step status disabled: server addres is empty'}      | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: '', error: null } }}                                                                                                                | ${'disabled'}
    ${'Credentials step status disabled: server addres has error'}     | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: 'error' } }}                                                                                      | ${'disabled'}
    ${'Credentials step status current: username is empty'}            | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: '', error: null }, password: { value: '', error: null } }}             | ${'current'}
    ${'Credentials step status current: username has error'}           | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: '', error: 'error' }, password: { value: '', error: null } }}          | ${'current'}
    ${'Credentials step status current: password is empty'}            | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: '', error: null } }}         | ${'current'}
    ${'Credentials step status current: password has error'}           | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: '', error: 'error' } }}      | ${'current'}
    ${'Credentials step status complete'}                              | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null } }} | ${'complete'}
  `('$title', ({ form, resultStatus }) => {
    expect(getServerCredentialsStepStatus(form)).toBe(resultStatus);
  });

  it.each`
    title                                                            | form                                                                                                                                                                                                                                                                                                                                                                                                  | installCommandWasCopied | resultStatus
    ${'Optionals step status disabled: no operating system defined'} | ${{ operatingSystemSelection: { value: '', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null } }}                                                                                                                                                                                 | ${false}                | ${'disabled'}
    ${'Optionals step status disabled: operating system has error'}  | ${{ operatingSystemSelection: { value: '', error: 'error' }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null } }}                                                                                                                                                                              | ${false}                | ${'disabled'}
    ${'Optionals step status disabled: server address is empty'}     | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: '', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null } }}                                                                                                                                                                                                    | ${false}                | ${'disabled'}
    ${'Optionals step status disabled: server address has error'}    | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost', error: 'error' }, username: { value: 'user', error: null }, password: { value: 'password', error: null } }}                                                                                                                                                                                | ${false}                | ${'disabled'}
    ${'Optionals step status disabled: username is empty'}           | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: 'error' }, username: { value: '', error: null }, password: { value: 'password', error: null } }}                                                                                                                                                                              | ${false}                | ${'disabled'}
    ${'Optionals step status disabled: username has error'}          | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: 'error' }, username: { value: 'user', error: 'error' }, password: { value: 'password', error: null } }}                                                                                                                                                                       | ${false}                | ${'disabled'}
    ${'Optionals step status disabled: password is empty'}           | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: 'error' }, username: { value: 'user', error: null }, password: { value: '', error: null } }}                                                                                                                                                                                  | ${false}                | ${'disabled'}
    ${'Optionals step status disabled: password has error'}          | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: 'error' }, username: { value: 'user', error: null }, password: { value: 'password', error: 'error' } }}                                                                                                                                                                       | ${false}                | ${'disabled'}
    ${'Optionals step status complete: install command was copied'}  | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null } }}                                                                                                                                                                             | ${true}                 | ${'complete'}
    ${'Optionals step status current: agent name is empty'}          | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: '', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}         | ${false}                | ${'current'}
    ${'Optionals step status current: agent name has error'}         | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: 'error' }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }} | ${false}                | ${'current'}
    ${'Optionals step status current: verificationMode is empty'}    | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: '', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}        | ${false}                | ${'current'}
    ${'Optionals step status current: verificationMode has error'}   | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: '', error: 'error' }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}     | ${false}                | ${'current'}
    ${'Optionals step status current: enrollmentKey is empty'}       | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: '', error: null }, enrollmentKey: { value: '', error: null } }}                                        | ${false}                | ${'current'}
    ${'Optionals step status current: enrollmentKey has error'}      | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: '', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: 'error' } }}     | ${false}                | ${'current'}
    ${'Optionals step status complete: '}                            | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}    | ${false}                | ${'complete'}
  `('$title', ({ form, installCommandWasCopied, resultStatus }) => {
    expect(getOptionalParameterStepStatus(form, installCommandWasCopied)).toBe(
      resultStatus,
    );
  });

  it.each`
    title                                                                                        | form                                                                                                                                                                                                                                                                                                                                                                                                     | resultStatus
    ${'Show install/start commands: no operating system defined'}                                | ${{ operatingSystemSelection: { value: '', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}           | ${false}
    ${'Show install/start commands: operating system has error'}                                 | ${{ operatingSystemSelection: { value: '', error: 'error' }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}        | ${false}
    ${'Show install/start commands: server address is empty'}                                    | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: '', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}                              | ${false}
    ${'Show install/start commands: server address has error'}                                   | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost', error: 'error' }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}          | ${false}
    ${'Show install/start commands: username is empty'}                                          | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: 'error' }, username: { value: '', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}        | ${false}
    ${'Show install/start commands: username has error'}                                         | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: 'error' }, username: { value: 'user', error: 'error' }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }} | ${false}
    ${'Show install/start commands: password is empty'}                                          | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: 'error' }, username: { value: 'user', error: null }, password: { value: '', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}            | ${false}
    ${'Show install/start commands: password has error'}                                         | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: 'error' }, username: { value: 'user', error: null }, password: { value: 'password', error: 'error' }, agentName: { value: 'agent', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }} | ${false}
    ${'Show install/start commands: agent name is empty'}                                        | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: '', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}            | ${true}
    ${'Show install/start commands: agent name has error'}                                       | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: 'error' }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}    | ${false}
    ${'Show install/start commands: verification mode is empty'}                                 | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: '', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}           | ${true}
    ${'Show install/start commands: verification mode has error'}                                | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: '', error: 'error' }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}        | ${false}
    ${'Show install/start commands: enrollment key is empty'}                                    | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: '', error: null }, enrollmentKey: { value: '', error: null } }}                                           | ${true}
    ${'Show install/start commands: enrollment key has error'}                                   | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: '', error: null }, enrollmentKey: { value: '0000', error: 'error' } }}                                    | ${false}
    ${'Show install/start commands: agent name, verification mode and enrollment key are empty'} | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: '', error: null }, verificationMode: { value: '', error: null }, enrollmentKey: { value: '', error: null } }}                                                | ${true}
  `('$title', ({ form, resultStatus }) => {
    expect(showCommandsSections(form)).toBe(resultStatus);
  });

  it.each`
    title                                                                                       | form                                                                                                                                                                                                                                                                                                                                                                                                     | installCommandWasCopied | resultStatus
    ${'Agent commands step status: no operating system defined'}                                | ${{ operatingSystemSelection: { value: '', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}           | ${false}                | ${'disabled'}
    ${'Agent commands step status: operating system has error'}                                 | ${{ operatingSystemSelection: { value: '', error: 'error' }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}        | ${false}                | ${'disabled'}
    ${'Agent commands step status: server address is empty'}                                    | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: '', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}                              | ${false}                | ${'disabled'}
    ${'Agent commands step status: server address has error'}                                   | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost', error: 'error' }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}          | ${false}                | ${'disabled'}
    ${'Agent commands step status: username is empty'}                                          | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: 'error' }, username: { value: '', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}        | ${false}                | ${'disabled'}
    ${'Agent commands step status: username has error'}                                         | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: 'error' }, username: { value: 'user', error: 'error' }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }} | ${false}                | ${'disabled'}
    ${'Agent commands step status: password is empty'}                                          | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: 'error' }, username: { value: 'user', error: null }, password: { value: '', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}            | ${false}                | ${'disabled'}
    ${'Agent commands step status: password has error'}                                         | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: 'error' }, username: { value: 'user', error: null }, password: { value: 'password', error: 'error' }, agentName: { value: 'agent', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }} | ${false}                | ${'disabled'}
    ${'Agent commands step status: agent name is empty'}                                        | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: '', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}            | ${false}                | ${'current'}
    ${'Agent commands step status: agent name is empty'}                                        | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: '', error: null }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}            | ${true}                 | ${'complete'}
    ${'Agent commands step status: agent name has error'}                                       | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: 'error' }, verificationMode: { value: 'none', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}    | ${false}                | ${'disabled'}
    ${'Agent commands step status: verification mode is empty'}                                 | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: '', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}           | ${false}                | ${'current'}
    ${'Agent commands step status: verification mode is empty'}                                 | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: '', error: null }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}           | ${true}                 | ${'complete'}
    ${'Agent commands step status: verification mode has error'}                                | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: '', error: 'error' }, enrollmentKey: { value: '00000000000000000000000000000000', error: null } }}        | ${false}                | ${'disabled'}
    ${'Agent commands step status: enrollment key is empty'}                                    | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: '', error: null }, enrollmentKey: { value: '', error: null } }}                                           | ${false}                | ${'current'}
    ${'Agent commands step status: enrollment key is empty'}                                    | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: '', error: null }, enrollmentKey: { value: '', error: null } }}                                           | ${true}                 | ${'complete'}
    ${'Agent commands step status: enrollment key has error'}                                   | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: 'agent', error: null }, verificationMode: { value: '', error: null }, enrollmentKey: { value: '0000', error: 'error' } }}                                    | ${false}                | ${'disabled'}
    ${'Agent commands step status: agent name, verification mode and enrollment key are empty'} | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: '', error: null }, verificationMode: { value: '', error: null }, enrollmentKey: { value: '', error: null } }}                                                | ${false}                | ${'current'}
    ${'Agent commands step status: agent name, verification mode and enrollment key are empty'} | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null }, agentName: { value: '', error: null }, verificationMode: { value: '', error: null }, enrollmentKey: { value: '', error: null } }}                                                | ${true}                 | ${'complete'}
  `(
    '$title: $resultStatus',
    ({ form, installCommandWasCopied, resultStatus }) => {
      console.log({ installCommandWasCopied });
      expect(getAgentCommandsStepStatus(form, installCommandWasCopied)).toBe(
        resultStatus,
      );
    },
  );

  it.each`
    title                                                                                   | form                                                                                                                                                                                                                  | resultStatus
    ${'Get incomplete steps: missing operating system'}                                     | ${{ operatingSystemSelection: { value: '', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null } }} | ${['operating system']}
    ${'Get incomplete steps: missing server address'}                                       | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: '', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null } }}                    | ${['server address']}
    ${'Get incomplete steps: missing username'}                                             | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: '', error: null }, password: { value: 'password', error: null } }} | ${['username']}
    ${'Get incomplete steps: missing password'}                                             | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: '', error: null } }}     | ${['password']}
    ${'Get incomplete steps: missing operating system, server address, username, password'} | ${{ operatingSystemSelection: { value: '', error: null }, serverAddress: { value: '', error: null }, username: { value: '', error: null }, password: { value: '', error: null } }}                                    | ${['operating system', 'server address', 'username', 'password']}
    ${'Get incomplete steps: missing operating system, server address, username'}           | ${{ operatingSystemSelection: { value: '', error: null }, serverAddress: { value: '', error: null }, username: { value: '', error: null }, password: { value: 'password', error: null } }}                            | ${['operating system', 'server address', 'username']}
    ${'Get incomplete steps: missing operating system, server address'}                     | ${{ operatingSystemSelection: { value: '', error: null }, serverAddress: { value: '', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: null } }}                        | ${['operating system', 'server address']}
    ${'Get incomplete steps: missing operating system, username'}                           | ${{ operatingSystemSelection: { value: '', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: '', error: null }, password: { value: 'password', error: null } }}     | ${['operating system', 'username']}
  `('$title', ({ form, resultStatus }) => {
    expect(getIncompleteSteps(form)).toEqual(resultStatus);
  });

  it.each`
    title                                                              | form                                                                                                                                                                                                                            | resultStatus
    ${'Get invalid steps: invalid server address'}                     | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: 'error' }, username: { value: 'user', error: null }, password: { value: 'password', error: null } }}    | ${['server address']}
    ${'Get invalid steps: invalid username'}                           | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: 'error' }, password: { value: 'password', error: null } }}    | ${['username']}
    ${'Get invalid steps: invalid password'}                           | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: null }, username: { value: 'user', error: null }, password: { value: 'password', error: 'error' } }}    | ${['password']}
    ${'Get invalid steps: invalid server address, username, password'} | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: 'error' }, username: { value: '', error: 'error' }, password: { value: '', error: 'error' } }}          | ${['server address', 'username', 'password']}
    ${'Get invalid steps: invalid  server address, username'}          | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: 'error' }, username: { value: 'user', error: 'error' }, password: { value: 'password', error: null } }} | ${['server address', 'username']}
    ${'Get invalid steps: invalid server address'}                     | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: 'error' }, username: { value: 'user', error: null }, password: { value: 'password', error: null } }}    | ${['server address']}
    ${'Get invalid steps: invalid server address, username'}           | ${{ operatingSystemSelection: { value: 'test', error: null }, serverAddress: { value: 'https://localhost:55000', error: 'error' }, username: { value: 'user', error: 'error' }, password: { value: 'password', error: null } }} | ${['server address', 'username']}
  `('$title', ({ form, resultStatus }) => {
    expect(getInvalidFields(form)).toEqual(resultStatus);
  });
});
