/*
 * Wazuh app - Module for ISO 27001 requirements
 * Copyright (C) 2015-2026 Wazuh, Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Find more information about this on the LICENSE file.
 */

/*
 * This file is generated by scripts/generate-compliance-data.js. Do not edit it
 * by hand: edit the catalog in wazuh/intelligence-data and regenerate.
 *
 * Framework: iso_27001
 * Edition: 2022
 * Source: ISO/IEC 27002:2022(E) Information security controls, official preview pages (table of contents), published by ISO/IEC and distributed by ANSI
 * Controls: 93
 */
import { ComplianceRequirement } from './types';

export const iso27001RequirementsFile: Record<string, ComplianceRequirement> = {
  'A.5.1': {
    title: 'Policies for information security',
    description:
      'The organization keeps a written security policy plus supporting policies on specific topics, all approved by management. The people who must follow them know them, and they are reviewed on a schedule and after major changes.',
  },
  'A.5.2': {
    title: 'Information security roles and responsibilities',
    description:
      'Every security task has a named owner. Who does what to protect information, and with what authority, is written down and given to specific people.',
  },
  'A.5.3': {
    title: 'Segregation of duties',
    description:
      'Tasks that could conflict, such as requesting and approving the same change, are split between different people. This limits fraud, abuse and mistakes that nobody notices.',
  },
  'A.5.4': {
    title: 'Management responsibilities',
    description:
      'Managers require staff and contractors to follow the security policy and procedures, and they lead by example in applying them day to day.',
  },
  'A.5.5': {
    title: 'Contact with authorities',
    description:
      'The organization knows which regulators, law enforcement and other public bodies it must contact about security matters, and keeps those contacts current.',
  },
  'A.5.6': {
    title: 'Contact with special interest groups',
    description:
      'Security staff stay connected with industry groups, forums and professional associations to share knowledge, receive early warnings and keep their skills up to date.',
  },
  'A.5.7': {
    title: 'Threat intelligence',
    description:
      'Information about current and emerging threats is gathered and analysed, and the results are used to adjust defences and security decisions.',
  },
  'A.5.8': {
    title: 'Information security in project management',
    description:
      'Security is built into every project from planning to closure, whatever the type of project. Project risks to information are identified and handled as part of the project work.',
  },
  'A.5.9': {
    title: 'Inventory of information and other associated assets',
    description:
      'An up-to-date list of information, systems and other assets is maintained, and each item has an owner who is accountable for its protection.',
  },
  'A.5.10': {
    title: 'Acceptable use of information and other associated assets',
    description:
      'People know what they may and may not do with company information, devices and other assets. Written rules and handling procedures cover allowed use, and they are applied in daily work.',
  },
  'A.5.11': {
    title: 'Return of assets',
    description:
      'When people leave, change role, or a contract or agreement ends, they give back the company devices, data and other assets they hold, and this return is checked.',
  },
  'A.5.12': {
    title: 'Classification of information',
    description:
      'Each item of information gets a sensitivity level set by how much harm its disclosure, corruption or loss would cause, plus legal and stakeholder demands. The level then decides how it is protected.',
  },
  'A.5.13': {
    title: 'Labelling of information',
    description:
      'Information carries marks that show its classification, applied through agreed procedures, so anyone handling it knows how to treat it.',
  },
  'A.5.14': {
    title: 'Information transfer',
    description:
      'Moving information inside the organization or to outside parties, by any channel, follows defined rules, procedures or agreements that keep it protected in transit.',
  },
  'A.5.15': {
    title: 'Access control',
    description:
      'Who may reach information and systems, physically and logically, is decided by business and security needs and written into access rules.',
  },
  'A.5.16': {
    title: 'Identity management',
    description:
      'Identities of users and systems are created, maintained and retired through a managed lifecycle, so each account maps to one accountable person or process.',
  },
  'A.5.17': {
    title: 'Authentication information',
    description:
      'Passwords, keys, tokens and other secrets are issued, changed and revoked through a controlled process, and users are told how to keep them safe.',
  },
  'A.5.18': {
    title: 'Access rights',
    description:
      'Each user gets only the permissions their job needs. Permissions are checked on a schedule, updated when someone moves roles, and taken away when they are no longer justified.',
  },
  'A.5.19': {
    title: 'Information security in supplier relationships',
    description:
      'Risks that come from using the products and services of suppliers are identified, and processes are in place to keep those risks under control.',
  },
  'A.5.20': {
    title: 'Addressing information security within supplier agreements',
    description:
      'Contracts with each supplier state the security requirements that apply to that relationship, so obligations on both sides are clear and enforceable.',
  },
  'A.5.21': {
    title: 'Managing information security in the ICT supply chain',
    description:
      'Security risks in the chain of technology products and services, including components that suppliers source from others, are identified and managed.',
  },
  'A.5.22': {
    title: 'Monitoring, review and change management of supplier services',
    description:
      'Supplier security practices and service delivery are checked regularly, and changes to supplier services are assessed and controlled before they take effect.',
  },
  'A.5.23': {
    title: 'Information security for use of cloud services',
    description:
      "Cloud services are chosen, run and exited under agreed processes that reflect the organization's security needs. This covers shared responsibility with the provider and a plan to move data out safely.",
  },
  'A.5.24': {
    title: 'Information security incident management planning and preparation',
    description:
      'Before any incident happens, the organization sets up its incident handling process, names who does what, and tells those people. This lets the team respond fast and consistently when an incident occurs.',
  },
  'A.5.25': {
    title: 'Assessment and decision on information security events',
    description:
      'Security events are evaluated to decide whether they count as incidents, so real incidents are recognised early and handled quickly.',
  },
  'A.5.26': {
    title: 'Response to information security incidents',
    description:
      'Confirmed incidents are handled by following documented response procedures, from first containment through to full recovery.',
  },
  'A.5.27': {
    title: 'Learning from information security incidents',
    description:
      'Lessons from past incidents are fed back into the security controls to reduce the chance or the impact of similar incidents in the future.',
  },
  'A.5.28': {
    title: 'Collection of evidence',
    description:
      'When an event may lead to legal or disciplinary action, evidence is gathered and preserved through defined procedures so it stays trustworthy.',
  },
  'A.5.29': {
    title: 'Information security during disruption',
    description:
      'Security stays at a suitable level during disruptions, with plans that keep protection in place while the organization recovers.',
  },
  'A.5.30': {
    title: 'ICT readiness for business continuity',
    description:
      'Technology services are prepared, tested and kept ready so they can support business continuity objectives during and after a disruption.',
  },
  'A.5.31': {
    title: 'Legal, statutory, regulatory and contractual requirements',
    description:
      'The organization keeps a current register of the laws, regulations and contract terms that bear on information security, and records how it plans to comply with each one.',
  },
  'A.5.32': {
    title: 'Intellectual property rights',
    description:
      'Procedures protect intellectual property, such as software licences and copyrighted material, and prevent its unlawful use.',
  },
  'A.5.33': {
    title: 'Protection of records',
    description:
      'Business records are kept safe from being lost, altered, destroyed or seen by the wrong people for their full retention period.',
  },
  'A.5.34': {
    title: 'Privacy and protection of PII',
    description:
      'Personal data is handled in line with privacy laws, regulations and contracts, and the organization can show that it meets those obligations.',
  },
  'A.5.35': {
    title: 'Independent review of information security',
    description:
      'An auditor or team not involved in the work checks the security management approach and how it runs in practice. This happens on a set schedule and whenever something important changes.',
  },
  'A.5.36': {
    title:
      'Compliance with policies, rules and standards for information security',
    description:
      'Regular checks confirm that people and systems actually follow the security policy, the topic rules and the agreed standards.',
  },
  'A.5.37': {
    title: 'Documented operating procedures',
    description:
      'Step-by-step instructions for running and maintaining systems, such as start-up, backup and recovery, are recorded and kept where the staff who use them can find them.',
  },
  'A.6.1': {
    title: 'Screening',
    description:
      'People are screened before they join and again over time where the role calls for it. Checks respect local law and ethics and scale with the job, the data accessed and the risks.',
  },
  'A.6.2': {
    title: 'Terms and conditions of employment',
    description:
      'Employment contracts set out the security responsibilities of both the employee and the organization, so each side knows its obligations from the first day.',
  },
  'A.6.3': {
    title: 'Information security awareness, education and training',
    description:
      'Everyone who handles company information, including relevant contractors, learns the security basics and the skills their job needs. Content is refreshed regularly as policies, procedures and threats change.',
  },
  'A.6.4': {
    title: 'Disciplinary process',
    description:
      'A formal disciplinary process, known to all staff, deals with people who break the security policy and makes consequences predictable and fair.',
  },
  'A.6.5': {
    title: 'Responsibilities after termination or change of employment',
    description:
      'Some duties, like keeping company information secret, still apply after someone leaves or moves to another job. Those duties are explained to the person and followed up.',
  },
  'A.6.6': {
    title: 'Confidentiality or non-disclosure agreements',
    description:
      'Staff, contractors and partners sign non-disclosure terms that match how sensitive the information they handle is. The terms are kept on record and revisited when needs change or on a periodic basis.',
  },
  'A.6.7': {
    title: 'Remote working',
    description:
      'Remote and home workers follow security measures that protect the company information they use outside the office.',
  },
  'A.6.8': {
    title: 'Information security event reporting',
    description:
      'Staff have a clear and quick channel to report any security event they observe or suspect, so it reaches the right people in time.',
  },
  'A.7.1': {
    title: 'Physical security perimeters',
    description:
      'Areas that hold information and systems are enclosed by defined physical boundaries, such as walls, fences or controlled doors, that match the value of what they protect.',
  },
  'A.7.2': {
    title: 'Physical entry',
    description:
      'Entry points and physical access controls, such as badges or locks, ensure that only authorised people get into secure areas.',
  },
  'A.7.3': {
    title: 'Securing offices, rooms and facilities',
    description:
      'Offices, rooms and facilities are designed and built with physical protection that fits the sensitivity of the information and equipment they contain.',
  },
  'A.7.4': {
    title: 'Physical security monitoring',
    description:
      'Premises are watched continuously, for example with cameras, guards or alarms, to detect unauthorised physical access.',
  },
  'A.7.5': {
    title: 'Protecting against physical and environmental threats',
    description:
      'Facilities are protected against natural disasters, fire, flooding, power problems and deliberate physical attacks on the infrastructure.',
  },
  'A.7.6': {
    title: 'Working in secure areas',
    description:
      'Specific rules govern how people work inside secure areas, such as supervision of visitors and limits on recording devices, and those rules are applied.',
  },
  'A.7.7': {
    title: 'Clear desk and clear screen',
    description:
      'Desks are kept free of papers and removable media, and screens are locked or cleared whenever they are left unattended.',
  },
  'A.7.8': {
    title: 'Equipment siting and protection',
    description:
      'Equipment is placed and protected in a way that reduces physical and environmental risks and prevents unauthorised access to it.',
  },
  'A.7.9': {
    title: 'Security of assets off-premises',
    description:
      'Laptops and other assets used away from company sites are protected against loss, theft and misuse.',
  },
  'A.7.10': {
    title: 'Storage media',
    description:
      'Removable and fixed storage media are tracked from purchase to disposal. Their use, transport and destruction follow the handling rules for the classification of the data they hold.',
  },
  'A.7.11': {
    title: 'Supporting utilities',
    description:
      'Systems are shielded from outages of electricity, cooling, water or telecommunications, through measures like backup power and regular checks of these services.',
  },
  'A.7.12': {
    title: 'Cabling security',
    description:
      'Power and data cables are routed and protected so they cannot easily be tapped, disrupted or physically damaged.',
  },
  'A.7.13': {
    title: 'Equipment maintenance',
    description:
      'Hardware receives upkeep according to supplier guidance and by authorised staff, so faults do not cause data loss, corruption or exposure.',
  },
  'A.7.14': {
    title: 'Secure disposal or re-use of equipment',
    description:
      'Before any device with storage is thrown away or reused, staff confirm that licensed programs and sensitive data on it have been wiped or destroyed beyond recovery.',
  },
  'A.8.1': {
    title: 'User endpoint devices',
    description:
      'Laptops, phones and other user devices are configured and managed so the company data they hold or can reach stays protected.',
  },
  'A.8.2': {
    title: 'Privileged access rights',
    description:
      'Administrator and other privileged accounts are limited to the people who need them, granted only for that need and closely managed.',
  },
  'A.8.3': {
    title: 'Information access restriction',
    description:
      'Each user can open only the data and application functions their role allows, as set by the access control policy.',
  },
  'A.8.4': {
    title: 'Access to source code',
    description:
      'Only authorised developers and tools can view or change the code base, build tooling and shared libraries. This prevents unauthorised changes, hidden functionality and leaks of intellectual property.',
  },
  'A.8.5': {
    title: 'Secure authentication',
    description:
      'Users and systems prove who they are through strong authentication, such as multi-factor login, matched to the sensitivity of what they access.',
  },
  'A.8.6': {
    title: 'Capacity management',
    description:
      'Teams watch how much processing, storage, network and staff capacity is used, and plan ahead so resources keep pace with demand.',
  },
  'A.8.7': {
    title: 'Protection against malware',
    description:
      'Technical defences against malware are in place on systems and networks, and users are made aware of how malware spreads.',
  },
  'A.8.8': {
    title: 'Management of technical vulnerabilities',
    description:
      'The organization tracks newly published weaknesses in the software and hardware it runs, judges how exposed it is to each, and patches or mitigates them in time.',
  },
  'A.8.9': {
    title: 'Configuration management',
    description:
      'Systems, applications and network devices run from approved, documented baseline settings, and changes from that baseline are monitored and reviewed.',
  },
  'A.8.10': {
    title: 'Information deletion',
    description:
      'Data that has no further business or legal purpose is securely erased from systems, devices and storage media.',
  },
  'A.8.11': {
    title: 'Data masking',
    description:
      'Sensitive data is masked or hidden in line with access policies, business needs and legal requirements.',
  },
  'A.8.12': {
    title: 'Data leakage prevention',
    description:
      'Measures detect and stop sensitive information from being disclosed or extracted without authorisation from systems, networks and devices.',
  },
  'A.8.13': {
    title: 'Information backup',
    description:
      'The organization keeps copies of its data, software and system images as its backup policy sets out, and restores from them on a regular basis to prove the copies work.',
  },
  'A.8.14': {
    title: 'Redundancy of information processing facilities',
    description:
      'Processing facilities are built with enough duplicate components and capacity to keep services running when a single part fails.',
  },
  'A.8.15': {
    title: 'Logging',
    description:
      'Systems keep records of user actions, errors and security events. Those records are protected from tampering and are reviewed to spot problems.',
  },
  'A.8.16': {
    title: 'Monitoring activities',
    description:
      'Teams look for unusual behaviour in network traffic, systems and applications, and investigate alerts to decide whether an incident is under way.',
  },
  'A.8.17': {
    title: 'Clock synchronization',
    description:
      'All systems take their time from agreed reference clocks, so timestamps match and events from different systems can be put in the right order.',
  },
  'A.8.18': {
    title: 'Use of privileged utility programs',
    description:
      'Utilities that can bypass operating system or application security controls are available to very few authorised administrators, and each use is limited, approved and logged.',
  },
  'A.8.19': {
    title: 'Installation of software on operational systems',
    description:
      'Installing software on production systems follows procedures and controls that keep those systems secure and stable.',
  },
  'A.8.20': {
    title: 'Networks security',
    description:
      'Network infrastructure, including routers, switches and firewalls, is hardened, administered and supervised so that the data flowing between connected systems stays protected from compromise.',
  },
  'A.8.21': {
    title: 'Security of network services',
    description:
      'Each network service, whether run in-house or bought from a provider, has agreed security functions and service levels. These are put in place and tracked so the service keeps meeting them.',
  },
  'A.8.22': {
    title: 'Segregation of networks',
    description:
      'Networks are divided into separate zones, for example by function or sensitivity, so users and systems only reach the segments they need.',
  },
  'A.8.23': {
    title: 'Web filtering',
    description:
      'Access to external websites is restricted, for example by category or reputation, so users are less exposed to malware, phishing and other harmful content.',
  },
  'A.8.24': {
    title: 'Use of cryptography',
    description:
      'The organization decides where encryption and other cryptography are used, and how keys are generated, stored, rotated and destroyed, and then follows those rules.',
  },
  'A.8.25': {
    title: 'Secure development life cycle',
    description:
      'Software and systems are developed following secure development rules at every stage of their lifecycle, from design to retirement.',
  },
  'A.8.26': {
    title: 'Application security requirements',
    description:
      'Before an application is built or bought, its security needs, such as login, input checks and data protection, are worked out, written into the requirements and signed off.',
  },
  'A.8.27': {
    title: 'Secure system architecture and engineering principles',
    description:
      'The organization sets secure design principles, such as defence in depth and least privilege, and every new or changed system follows them. The principles are kept current as threats and technology change.',
  },
  'A.8.28': {
    title: 'Secure coding',
    description:
      'Developers write code following secure coding practices, so common weaknesses are not introduced into the software.',
  },
  'A.8.29': {
    title: 'Security testing in development and acceptance',
    description:
      'Security tests are planned and run during development, and systems pass security acceptance checks before going live.',
  },
  'A.8.30': {
    title: 'Outsourced development',
    description:
      'When software is built by an outside company, the organization sets the security terms, oversees the work and checks the delivered result against its security requirements.',
  },
  'A.8.31': {
    title: 'Separation of development, test and production environments',
    description:
      'Code is built and tested in environments kept apart from live systems, so work in progress cannot affect production and each environment has its own protection.',
  },
  'A.8.32': {
    title: 'Change management',
    description:
      'Changes to systems and processing facilities go through a formal change management process with review and approval before release.',
  },
  'A.8.33': {
    title: 'Test information',
    description:
      'Data used in testing is picked with care and given the same protection as live data. Real personal or confidential data is avoided or masked where possible.',
  },
  'A.8.34': {
    title: 'Protection of information systems during audit testing',
    description:
      'Audit work and technical testing on live systems are scoped, scheduled and approved by system owners and management beforehand, so they cause as little disruption as possible.',
  },
};
