---
plugin: openapi
specFile: https://raw.githubusercontent.com/wazuh/wazuh/v4.4.0/api/api/spec/spec.yaml

resources:
  - path: /security/user/authenticate
    method: post
    response:
      statusCode: 200
      scriptFile: login.js
  - path: /
    method: get
    response:
      statusCode: 200
      staticFile: api_info.json
