Vagrant.configure("2") do |config|

  config.vm.box = "generic/freebsd12"
    config.vm.define "freebsd12"
    config.vm.network "private_network", ip: "192.168.50.50"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = "2"
        #vb.gui = true 
    end

   config.vm.provision "shell", inline: <<-SHELL
      sudo pkg pkg update -f
      sudo pkg install -y gmake gcc automake libtool readline cmake nano git
      git clone https://github.com/wazuh/wazuh.git wazuh
      cd wazuh
      git checkout tags/v4.2.2 
   SHELL
end
