export const DECODERS_PAGE = {
  titleSelector: '[class="euiTitle euiTitle--medium"]',
  tableSelector: '[class="euiTableRow customRowClass euiTableRow-isClickable"]',
  dropdownPaginationSelector: '[data-test-subj="tablePaginationPopoverButton"]',
  listPages: 'nav[class="euiPagination"]',
  customDecodersButtonSelector: '[data-test-subj="Custom decoders"]',
  manageDecodersFilesButtonSelector: '.euiButtonEmpty .euiButtonContent .euiButtonEmpty__text:contains("Manage decoders")',
  editDecoderButtonSelector: 'tr.euiTableRow:nth-child(1) .euiToolTipAnchor .euiButtonIcon[aria-label="Edit content"]',
  saveDecoderButtonSelector: '.euiFlexGroup .euiFlexItem button.euiButton span.euiButtonContent span.euiButton__text:contains("Save")',
  messageConfirmSaveSelector: '.euiText > span',
  buttonRestartSelector: '.euiCallOut.euiCallOut--primary .euiButton.euiButton--primary',
  firstCustomDecoder: '[data-test-subj="row-local_decoder_example"]',
  xmlDecoderFile:':nth-child(4) .euiTableCellContent .euiToolTipAnchor .euiLink:contains("local_decoder.xml")',
  codeEditorSelector: '[data-test-subj="codeEditorContainer"]',
  backButtonSelector: '.euiFlexGroup .euiFlexItem .euiToolTipAnchor .euiButtonIcon',
  confirmModalSelector: '[data-test-subj="confirmModalTitleText"]',
  createNewDecoderSelector:'.euiFlexGroup .euiFlexItem .euiButtonEmpty .euiButtonContent .euiButtonEmpty__text:contains("Add new decoders file")',
  decoderTitleSelector: '.euiFlexItem .euiFlexGroup .euiFormControlLayout input.euiFieldText',
  saveDecoderMessage: '.euiText span:contains("Changes will not take effect until a restart is performed.")'
};
