version: '3'

# Parameters:
# -------------
#   - REPO:         Path to the Wazuh app local repository

services:
  docs-url-checks:
    build:
      context: ${REPO}
      dockerfile: docker/url-checks/Dockerfile.docs
    tty: true

  others-url-checks:
    build:
      context: ${REPO}
      dockerfile: docker/url-checks/Dockerfile.others
    tty: true
