version: '3'

# Parameters:
# -------------
#   - REPO:         Path to the Wazuh app local repository
#   - NODE_VERSION: Node.js version (default: 20)

services:
  extracted-urls:
    image: node:${NODE_VERSION:-20}-alpine
    working_dir: /app
    volumes:
      - ${REPO}:/app
    command: |
      /bin/sh -c '
        npm install -g tsx typescript --no-package-lock &&
        tsx scripts/url-checks-extractor.ts
        '

  url-checks:
    image: lycheeverse/lychee
    depends_on:
      extracted-urls:
        condition: service_completed_successfully
    working_dir: /app
    volumes:
      - ${REPO}:/app
    tty: true
    command: --max-redirects 0 --format detailed --no-progress scripts/extracted-urls.md
