version: '3'

# Parameters:
# -------------
#   - REPO:     Path to the Wazuh app local repository
#   - NODE_VERSION: Node.js version to use (default: 20)

services:
  url_checks:
    container_name: url-checks
    image: node:${NODE_VERSION:-20}-alpine
    working_dir: /app
    volumes:
      - $REPO:/app/plugins/main
    tty: true
    command: /bin/sh -c '
      npm init -y;
      npm install ts-morph --no-package-lock --legacy-peer-deps;
      node plugins/main/scripts/url-checks-extractor.js
      '
