# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nlp_ims_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nlp_ims_request.proto',
  package='Application',
  syntax='proto3',
  serialized_options=_b('\n$com.splunk.mobile.nlp.service.iframeP\001Z>cd.splunkdev.com/mobile/spacebridge-golang-protos/splunkcx/ssg'),
  serialized_pb=_b('\n\x15nlp_ims_request.proto\x12\x0b\x41pplication\"X\n\x19ImsSingleUseTokenEnvelope\x12\x12\n\nserialized\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\x14\n\x0c\x64\x65ploymentId\x18\x03 \x01(\x0c\"M\n\x1bImsSingleUseTokenGetRequest\x12\x18\n\x10\x63\x61nManageIntents\x18\x01 \x01(\x08\x12\x14\n\x0cmappedUserId\x18\x02 \x01(\tBh\n$com.splunk.mobile.nlp.service.iframeP\x01Z>cd.splunkdev.com/mobile/spacebridge-golang-protos/splunkcx/ssgb\x06proto3')
)




_IMSSINGLEUSETOKENENVELOPE = _descriptor.Descriptor(
  name='ImsSingleUseTokenEnvelope',
  full_name='Application.ImsSingleUseTokenEnvelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serialized', full_name='Application.ImsSingleUseTokenEnvelope.serialized', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='Application.ImsSingleUseTokenEnvelope.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deploymentId', full_name='Application.ImsSingleUseTokenEnvelope.deploymentId', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=126,
)


_IMSSINGLEUSETOKENGETREQUEST = _descriptor.Descriptor(
  name='ImsSingleUseTokenGetRequest',
  full_name='Application.ImsSingleUseTokenGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='canManageIntents', full_name='Application.ImsSingleUseTokenGetRequest.canManageIntents', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mappedUserId', full_name='Application.ImsSingleUseTokenGetRequest.mappedUserId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=205,
)

DESCRIPTOR.message_types_by_name['ImsSingleUseTokenEnvelope'] = _IMSSINGLEUSETOKENENVELOPE
DESCRIPTOR.message_types_by_name['ImsSingleUseTokenGetRequest'] = _IMSSINGLEUSETOKENGETREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImsSingleUseTokenEnvelope = _reflection.GeneratedProtocolMessageType('ImsSingleUseTokenEnvelope', (_message.Message,), dict(
  DESCRIPTOR = _IMSSINGLEUSETOKENENVELOPE,
  __module__ = 'nlp_ims_request_pb2'
  # @@protoc_insertion_point(class_scope:Application.ImsSingleUseTokenEnvelope)
  ))
_sym_db.RegisterMessage(ImsSingleUseTokenEnvelope)

ImsSingleUseTokenGetRequest = _reflection.GeneratedProtocolMessageType('ImsSingleUseTokenGetRequest', (_message.Message,), dict(
  DESCRIPTOR = _IMSSINGLEUSETOKENGETREQUEST,
  __module__ = 'nlp_ims_request_pb2'
  # @@protoc_insertion_point(class_scope:Application.ImsSingleUseTokenGetRequest)
  ))
_sym_db.RegisterMessage(ImsSingleUseTokenGetRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
