# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metadata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import http_pb2 as http__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metadata.proto',
  package='Spacebridge',
  syntax='proto3',
  serialized_options=_b('\n/com.splunk.mobile.spacebridge.messages.metadataP\001ZFcd.splunkdev.com/mobile/spacebridge-golang-protos/splunkcx/spacebridge'),
  serialized_pb=_b('\n\x0emetadata.proto\x12\x0bSpacebridge\x1a\nhttp.proto\"\x1f\n\x1dGetSpacebridgeMetadataRequest\"|\n\x1eGetSpacebridgeMetadataResponse\x12\'\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x16.Spacebridge.HttpErrorH\x00\x12\x12\n\x08instance\x18\x02 \x01(\x0cH\x00\x12\x11\n\tsignature\x18\x03 \x01(\x0c\x42\n\n\x08responseB{\n/com.splunk.mobile.spacebridge.messages.metadataP\x01ZFcd.splunkdev.com/mobile/spacebridge-golang-protos/splunkcx/spacebridgeb\x06proto3')
  ,
  dependencies=[http__pb2.DESCRIPTOR,])




_GETSPACEBRIDGEMETADATAREQUEST = _descriptor.Descriptor(
  name='GetSpacebridgeMetadataRequest',
  full_name='Spacebridge.GetSpacebridgeMetadataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=74,
)


_GETSPACEBRIDGEMETADATARESPONSE = _descriptor.Descriptor(
  name='GetSpacebridgeMetadataResponse',
  full_name='Spacebridge.GetSpacebridgeMetadataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='Spacebridge.GetSpacebridgeMetadataResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instance', full_name='Spacebridge.GetSpacebridgeMetadataResponse.instance', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='Spacebridge.GetSpacebridgeMetadataResponse.signature', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='Spacebridge.GetSpacebridgeMetadataResponse.response',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=76,
  serialized_end=200,
)

_GETSPACEBRIDGEMETADATARESPONSE.fields_by_name['error'].message_type = http__pb2._HTTPERROR
_GETSPACEBRIDGEMETADATARESPONSE.oneofs_by_name['response'].fields.append(
  _GETSPACEBRIDGEMETADATARESPONSE.fields_by_name['error'])
_GETSPACEBRIDGEMETADATARESPONSE.fields_by_name['error'].containing_oneof = _GETSPACEBRIDGEMETADATARESPONSE.oneofs_by_name['response']
_GETSPACEBRIDGEMETADATARESPONSE.oneofs_by_name['response'].fields.append(
  _GETSPACEBRIDGEMETADATARESPONSE.fields_by_name['instance'])
_GETSPACEBRIDGEMETADATARESPONSE.fields_by_name['instance'].containing_oneof = _GETSPACEBRIDGEMETADATARESPONSE.oneofs_by_name['response']
DESCRIPTOR.message_types_by_name['GetSpacebridgeMetadataRequest'] = _GETSPACEBRIDGEMETADATAREQUEST
DESCRIPTOR.message_types_by_name['GetSpacebridgeMetadataResponse'] = _GETSPACEBRIDGEMETADATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetSpacebridgeMetadataRequest = _reflection.GeneratedProtocolMessageType('GetSpacebridgeMetadataRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETSPACEBRIDGEMETADATAREQUEST,
  __module__ = 'metadata_pb2'
  # @@protoc_insertion_point(class_scope:Spacebridge.GetSpacebridgeMetadataRequest)
  ))
_sym_db.RegisterMessage(GetSpacebridgeMetadataRequest)

GetSpacebridgeMetadataResponse = _reflection.GeneratedProtocolMessageType('GetSpacebridgeMetadataResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETSPACEBRIDGEMETADATARESPONSE,
  __module__ = 'metadata_pb2'
  # @@protoc_insertion_point(class_scope:Spacebridge.GetSpacebridgeMetadataResponse)
  ))
_sym_db.RegisterMessage(GetSpacebridgeMetadataResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
