# 📝 Based on: `4_builderprecompiled_base-dev-environment.yml`
#
# 📦 Manual Build Workflow for Wazuh Dashboard Plugins
#
# ⚡ Overview:
# This workflow builds and tests production-ready packages for Wazuh Dashboard plugins,
# either manually or triggered by other workflows.
#
# 🚀 Key Features:
# - 🖇️ Manual or Automated Builds: Supports manual execution or invocation from other workflows,
#   specifying any valid code reference (branch, tag, or commit SHA).
# - 🏗️ Production-Ready Package Generation: Builds a production-ready package from the provided code reference.
# - 🌐 Reusable Build Environment: Reuses a preconfigured build environment, ensuring consistency and easier maintenance.
# - 🧪 Automated Testing: Automatically downloads and tests generated artifacts using a dynamically configured Docker environment.
#

name: (4.x) Build app package (on demand)

on:
  workflow_call:
    inputs:
      reference:
        required: true
        type: string
        default: 4.14.0
        description: Source code reference (branch, tag or commit SHA)
      execution_repository:
        required: true
        type: string
        default: ''
        description: 'Repository and workflow run to upload the artifact to (format: repo/workflow). This is used to locate the artifacts in S3.'
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      reference:
        required: true
        type: string
        default: 4.14.0
        description: Source code reference (branch, tag or commit SHA)

env:
  CI_DEV_INTERNAL_BUCKET: ${{ secrets.CI_DEV_INTERNAL_BUCKET }}
  EXECUTION_REPOSITORY: 'wazuh-dashboard-plugins/4_builderpackage_plugins'

jobs:
  # Build an app package from the given source code reference.
  build:
    name: Build app package
    uses: ./.github/workflows/4_builderprecompiled_base-dev-environment.yml
    permissions:
      pull-requests: write
      id-token: write
    with:
      reference: ${{ inputs.reference }}
      command: 'yarn build'
      artifact_name: 'wazuh-dashboard-plugins'
      execution_repository: ${{ inputs.execution_repository || 'wazuh-dashboard-plugins/4_builderpackage_plugins' }}
    secrets: inherit

  test-packages:
    needs: build
    name: Test packages
    runs-on: codebuild-github-actions-codebuild-runner-dashboard-amd-${{ github.run_id }}-${{ github.run_attempt }}
    permissions:
      id-token: write

    steps:
      - name: Download the plugin's source code
        uses: actions/checkout@v4
        with:
          repository: wazuh/wazuh-dashboard-plugins
          ref: ${{ inputs.reference }}
          path: wazuh

      - name: Set variables
        run: |
          echo "githubReference=$(echo ${{ inputs.reference }} | sed 's/\//-/g')" >> $GITHUB_ENV
          echo "version=$(jq -r '.version' $(pwd)/wazuh/plugins/main/package.json)" >> $GITHUB_ENV
          echo "revision=$(jq -r '.revision' $(pwd)/wazuh/plugins/main/package.json)" >> $GITHUB_ENV
          echo "versionPlatform=$(jq -r '.pluginPlatform.version' $(pwd)/wazuh/plugins/main/package.json)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download plugin artifacts from S3
        run: |
          plugins_dir="${{ github.workspace }}/wazuh/scripts/test-packages/plugins"
          mkdir -p "${plugins_dir}"
          aws s3 cp --recursive \
            "${{ env.CI_DEV_INTERNAL_BUCKET }}/${{ inputs.execution_repository || env.EXECUTION_REPOSITORY }}/${{github.run_id}}" \
            "${plugins_dir}"
          ls -l "${plugins_dir}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          echo "current=${{ github.workspace }}"
          cd ./wazuh/scripts/test-packages
          docker build --build-arg OSD_VERSION=${{ env.versionPlatform }} -f osd-test-packages.Dockerfile ./
