# This workflow calls to `reusable-dev-environment` workflow to run build a package

name: Build package

on:
  workflow_dispatch:
    inputs:
      reference:
        required: true
        type: string
        default: master
        description: Branch/Tag/Commit SHA reference for the source code.

jobs:
  build-package-on-dispatch:
    name: Deploy a dev environment and build a package
    uses: ./.github/workflows/reusable-dev-environment.yml
    with:
      reference: ${{ github.event.inputs.reference }}
      command: 'yarn build'
      archive_name: 'wazuh-package'
      archive_path: './wazuh/build'
    secrets: inherit
