# This workflow calls to `reusable-dev-environment` workflow to run some command in a development enviroment

name: Dev env - Command

on:
  workflow_dispatch:
    inputs:
      reference:
        required: true
        type: string
        default: master
        description: Branch/Tag/Commit SHA reference for the source code.
      command:
        required: true
        type: string
        default: 'yarn test:jest'
        description: Docker run. Introduce the command to run.
      docker_run_extra_args:
        type: string
        default: ''
        description: Docker run. Extra arguments passed to the docker run command.
      archive_name:
        type: string
        default: ''
        description: Archive. Name of the archived file.
      archive_path:
        type: string
        default: ''
        description: Archive. Files path to archive.

jobs:
  command-dev-environment-on-dispatch:
    name: Deploy a dev environment and run a command
    uses: ./.github/workflows/reusable-dev-environment.yml
    with:
      reference: ${{ github.event.inputs.reference }}
      command: ${{ github.event.inputs.command }}
      docker_run_extra_args: ${{ github.event.inputs.docker_run_extra_args }}
      archive_name: ${{ github.event.inputs.archive_name }}
      archive_path: ${{ github.event.inputs.archive_path }}
    secrets: inherit
