name: URL Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check_urls:
    name: Check URLs
    runs-on: ubuntu-22.04
    if: github.event.pull_request.draft == false

    env:
      NODE_VERSION: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and run Docs URL checks
        run: |
          docker build -f docker/url-checks/Dockerfile.docs -t docs-url-checks .
          docker run --rm docs-url-checks

      - name: Build and run Others URL checks
        run: |
          docker build -f docker/url-checks/Dockerfile.others -t others-url-checks .
          docker run --rm others-url-checks
