# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Wazuh Unit Tests

on:
  push:
    branches:
      - 'disable'
  pull_request:
    branches:
      - '4.3-7.10'

jobs:
  setup-wazuh-app:
    name: Run setup environment wazuh app
    runs-on: ubuntu-18.04
    steps:
      - name: Step 01 - Download Project wazuh-app
        uses: actions/checkout@v2
      - name: Step 02 - Install dependencies
        run: |
          nvm use
          npm install
      - name: Step 03 - Run unit test
        run: |
          npm run test:jest
