# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Wazuh Unit Tests

on:
  push:
    branches:
      - 'disable'
  pull_request:
    branches:
      - '4.3-7.10'

jobs:
  setup-wazuh-app:
    name: Run setup environment wazuh app
    runs-on: ubuntu-18.04
    steps:
      - name: Step 01 - Download Project kibana
        uses: actions/checkout@v2
        with:
          repository: elastic/kibana
          ref: 'v7.10.2'
          path: kibana
      - name: Step 02 - Setup node for kibana app
        uses: actions/setup-node@v2
        with:
          node-version: '10.23.1'
      - name: Step 03 - Install dependencies of kibana
        run: |
          echo Kibana: $GITHUB_WORKSPACE
          cd kibana
          yarn set version 1.21.1
          yarn kbn bootstrap
          mkdir plugins/wazuh-kibana-app
      - name: Step 04 - Download Project wazuh-app
        uses: actions/checkout@v2
        with:
          path: kibana/plugins/wazuh-kibana-app
      - name: Step 05 - Setup node version for wazuh app
        uses: actions/setup-node@v2
        with:
          node-version: '12.22.3'
      - name: Step 06 - Install dependencies of wazuh
        run: |
          cd kibana/plugins/wazuh-kibana-app/
          yarn install
      - name: Step 07 - Setup node for Jest
        uses: actions/setup-node@v2
        with:
          node-version: '10.23.1'
      - name: PRUEBA
        run: |
          ls -la ./kibana/plugins/wazuh-kibana-app
      - name: Step 08 - Run unit test
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
          working-directory: ./kibana/plugins/wazuh-kibana-app
          threshold: 0.9 # value in percents'
          test-script: yarn run test:jest --silent --testLocationInResults --coverage --json --outputFile=report.json
